name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          set -eux
          # Install Playwright dependencies
          (mkdir /tmp/playwright-tmp && cd /tmp/playwright-tmp && npx playwright install --with-deps) &
          (npm ci) &
          wait
      - run: TS_NODE_COMPILER_OPTIONS='{"module":"commonjs"}' ./node_modules/.bin/ts-node tests/e2e/test.ts
