name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
#      - name: Install Playwright dependencies
#        run: |
#          sudo apt install -y libegl1\
#              libopus0\
#              libwoff1\
#              libharfbuzz-icu0\
#              gstreamer1.0-plugins-base\
#              libgstreamer-gl1.0-0\
#              gstreamer1.0-plugins-bad\
#              libopenjp2-7\
#              libwebpdemux2\
#              libenchant1c2a\
#              libhyphen0\
#              libgles2\
#              gstreamer1.0-libav
      - run: cd /tmp && npx playwright install --with-deps
      - run: npm ci
      - run: TS_NODE_COMPILER_OPTIONS='{"module":"commonjs"}' ./node_modules/.bin/ts-node tests/e2e/test.ts
